### ISSUE TITLE
not all symbols here

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/PyPascalTokenizer#11]
```
CHAPTER 1. PASCAL TOKENS
+ -
*
/ = < > [ ] . , ( ) : ^ @ { } $ # & %
and the following character pairs too:
<< >>
**
<> >< <= >= := += -=
*= /= (* *) (. .) //
```

Когда думал что все вспомнил

**Comment by Artem3213212** [comment]
у нас нет
`^ & % ** >< (. .) << >>`
можешь привести пример их использования? (про первый знаю)

**Comment by Alexey-T** [comment]
& для ескейпв имён / octal
% Binary notation
    ** power operator for classes
    >< set difference
(. .) are [ ]
<< >> are shl shr

**Comment by Artem3213212** [comment]
не правильно пофиксил

**Comment by Artem3213212** [comment]
& % не надо было добавлять

**Comment by Artem3213212** [comment]
я уже поправил
