### ISSUE TITLE
Parse error on some text

### ISSUE THREAD

**Issue by DKingAlpha** [Artem3213212/PyPascalTokenizer#14]
```
  //parse <Address>
  {
  //  <expression>
  //  [Rn]
  //  [Rn, offset] {!}
  //  [Rn,{+/-}Rm{,<shift>}]{!}
  }
```

This block of comment breaks it.

yeah, this never ends.

**Comment by Artem3213212** [comment]
this is not valid sintax:
Valid:
`  //parse <Address>
  {
  //  <expression>
  //  [Rn]
  //  [Rn, offset] {!}
  //  [Rn,{+/-}Rm{,<shift>}]{!}`
Tokens:
`//parse <Address>`
` {
  //  <expression>
  //  [Rn]
  //  [Rn, offset] {!}`
`//  [Rn,{+/-}Rm{,<shift>}]{!}`

**Comment by Alexey-T** [comment]
I don’t understand the report and Artem’s reply.

**Comment by DKingAlpha** [comment]
The code came from [Cheat Engine](https://github.com/cheat-engine/cheat-engine/blob/01177c0be7776d679694930fda70da4bcbb4f102/Cheat%20Engine/assemblerarm.pas#L657)

I was trying to parse the sources and do some string replacement. This block of code seems to have passed the compiling against lazarus-2.0.0-fpc-3.0.4 but still the syntax seems invalid to me. I will do some more research and reply here if I found anything.

**Comment by Alexey-T** [comment]
It is valid syntax, ie line comments inside curly comments. Artem, lib must handle this

**Comment by DKingAlpha** [comment]
I think I get it.
`}` in `  //  [Rn, offset] {!}` ends the comment block as a match for the first `{`
then `// any string and syntax except \n`
so the last `}` became invalid.

A possible solution is to skip the line starts with `//` while searching for `}` as the match for `{`, and I think its reasonable, but I dont know if this meets the standard of Pascal.

**Comment by DKingAlpha** [comment]
I tested the syntax in multiple online compilers (Github, rextester and onlinegdb ). Actually few of them handles this correctly.
All of them failed to parse this in frontend. In the backend, PPC(pico pascal compiler) failed to compile this, while FPC compiled it correctly.

**Comment by DKingAlpha** [comment]
[ISO 7158](http://pascal-central.com/docs/iso7185.pdf)(page 10) does not take // as a comment while Free Pascal Standard does. I guess it's up to you to decide whether to support it.

**Comment by Alexey-T** [comment]
Let’s not support this. Fail is reasonable.
