### ISSUE TITLE
is_comment 

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/PyPascalTokenizer#9]
def is_comment(s):
        return (s[0]=='{' and s[-1]=='}') or (s[:2]=='(*' and s[-2:]=='*)') or s[:2]=='//'

если токен точно валидный- мможно упростить-

return s.startswith('{') or s.startswith('(*') or s.startswith('//')

**Comment by Alexey-T** [comment]
и это

    def is_string(s):
        return s[0]=="'" and s[-1]=="'"

**Comment by Artem3213212** [comment]
если конец файла настал посередине комента то может вернуть не валидный
со строкой тоже самое

**Comment by Alexey-T** [comment]
Они даже тогда должны вернуть true

**Comment by Artem3213212** [comment]
тогда это вообще не пойми что так что сомнительно
